title: linaro-jekyll-theme (the advanced enterprise ready Jekyll theme)
url: http://jumbojekyll.co.uk
baseurl: ""
description: |-
  The linaro-jekyll-theme is an advanced enterprise ready Jekyll theme used across the Linaro static websites.
destination: _site
permalink: /:categories/:title/
theme: linaro-jekyll-theme
highlighter: rouge
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter: rouge
encoding: utf-8
safe: false
exclude:
  - Gemfile
  - Gemfile.lock
  - .asset_pipeline
  - .gitignore
  - .git
  - .asset-cache
  - _static-site
  - .sass-cache
  - _site
  - scripts
  - linaro-jekyll-theme*.gem
  - linaro-jekyll-theme*.gemspec
sass:
  style: compressed
  load_paths:
    - assets/css
  sourcemap: "never"
plugins:
  - japr
  - jekyll_picture_tag
  - jekyll-tidy
  - jekyll-toc
collections:
  authors:
    output: true
    permalink: /author/:name/
liquid:
  error_mode: strict
defaults:
  - scope:
      path: ""
    values:
      layout: flow
      lang: en
  - scope:
      type: posts
      path: "_posts"
    values:
      layout: post
      lang: en
      is_post: true
      comments: true
      tags_enabled: true
      strap_image: /assets/images/breadcrumb-image.jpg
  - scope:
      type: posts
      path: "_posts/ja"
    values:
      layout: post
      lang: ja
      is_post: true
      comments: true
      tags_enabled: true
      strap_image: /assets/images/breadcrumb-image.jpg
  - scope:
      path: ""
      type: "authors"
    values:
      layout: author
include: ["_pages"]
livereload_ignore:
  - .asset_pipeline/assets/js/*.js
  - .asset_pipeline/assets/js/*.js.gz
# ----------- THEME / WEBSITE CONFIG ---------------------
# Blog images/thumbs dir
blog_images_dir: assets/images/content/
# Blog Tag limit
tag_limit: 10
# The default number of posts to display on a given post index page
# used in the _includes/blog/display_latest_posts.html include
post_limit: 10
# Email
email: contact@linaro.org
# Company Address
address:
  - Harston Mill
  - Royston Rd, Harston
  - Cambridge, United Kingdom
  - CB22 7GG
# Support for http2 preload features
http2_resources:
  - rel: preload
    as: font
    type: font/woff2
    crossorigin: true
    href: /assets/fonts/lato/Lato-regular.woff2
google_analytics:
  enabled: true
  code: GTM-XXXX
  cookies:
    necessary:
      - name: cookieControl
        description: >
          This is used to control the display of the preferences pop up. Without this, we wouldn't know if you've clicked Accept!
      - name: cookieControlPrefs
        description: >
          This is used to store your cookie preferences. Without this we wouldn't know which cookies you want!
    marketing:
      - name: _ga
        description: >
          2 years - Used to distinguish users.
      - name: _gid
        description: >
          24 hours - Used to distinguish users.
      - name: _gat
        description: >
          1 minute - Used to throttle request rate.
# Set the site-wide default social media share image.
social_media_share_image: /assets/images/social-media-image.png
# Set the default favicon
favicon: /assets/images/favicon.png
# Toggle the animated navbar dropdown feature
# Navbar dropdowns will open on hover
hover_nav_dropdowns: true
# Set the class used to animate dropdowns e.g. fade-up / fade-down
nav_dropdowns_animation_class: fade-down
# The bootstrap breakpoint at which the navbars will expand
nav_expand_breakpoint: lg
# Site Name - your brand name
name: Jumbo Jekyll Theme
# The blog filler element
blog_filler_element: blog/blog_filler_element.html
# Breadcrumb banner image
breadcrumb_banner: /assets/images/breadcrumb-banner.png
# Placeholder avatar
avatar_placeholder: /assets/images/avatar-placeholder.jpg
# Blog Post Image Placholder
post_placeholder: /assets/images/breadcrumb-image.jpg
# Social Media Links
social_media_channels:
  github:
    url: https://github.com/Linaro
  linkedin:
    url: https://www.linkedin.com/company/1026961
  facebook:
    url: http://facebook.com/LinaroOrg
  youtube:
    url: https://www.youtube.com/linaroorg
  twitter:
    url: https://twitter.com/linaroorg
  instagram:
    url: https://instagram.com/linaroorg
# Disqus Comments Setup
disqus:
  enabled: true
  shortname: http-www-jumbojekyll-co-uk
# Edit on GitHub Settings
edit-on-github:
  enabled: true
  repo: https://www.github.com/linaro-marketing/linaro-jekyll-theme
  # docs: https://www.github.com/Linaro/website
# Page breadcrumb schema - https://schema.org/BreadcrumbList
breadcrumb_schema: true
# Shema.org settings used in the schema.html include.
schema:
  "@context": "https://schema.org"
  "@type": "Organization"
  "name": "Linaro"
  "url": "https://www.linaro.org"
  "email": "contact@linaro.org"
  "logo": "https://www.linaro.org/assets/images/content/linaro-logo.png"
  "contactPoint":
    "@type": "ContactPoint"
    "telephone": "01223 400060"
    "contactType": "customer service"
    "availableLanguage": "en"
  "sameAs": "https://www.linaro.org"
# FESS search label
search_label: Linaro
# ----------- JEKYLL PLUGINS ---------------------
# -------- jekyll-tidy --------
jekyll_tidy:
  # Toggle compression of HTML
  compress_html: true
  # JS Path added to exclude to stop errors.
  exclude: ["assets/**/*.js", "robots.txt", "admin/config.yml"]
autopages:
  enabled: false
# -------- jekyll_relative_links --------
jekyll_relative_links:
  process_all_collections: true
  verbose: 1
relative_links:
  enabled: true
  collections: false
# -------- jekyll_relative_links --------
readme_index:
  enabled: true
  remove_originals: false
# -------- jekyll_picture_tag --------
picture:
  nomarkdown: false
  source: ""
  output: "../generated"
  relative_url: true
# -------- japr --------
asset_pipeline:
  bundle: true
  compress: true
  output_path: assets/js
  gzip: false
# jekyll-toc
toc:
  min_level: 1
  max_level: 6
  ordered_list: false
  no_toc_section_class: no_toc_section
  list_class: list-group docs_nav sticky-top
  sublist_class: "list-group"
  item_class: toc-entry
  item_prefix: toc-
# Jekyll-polyglot
i18n_enabled: true
languages: ["en", "ja"]
default_lang: "en"
exclude_from_localization:
  ["javascript", "images", "css", "public", "assets", "generated"]
parallel_localization: false
